---
title: "Predicting Reddit Post Virality using Twitch Emotes"
author: "Michael Puerto"
date: "5/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Abstract

Twitch.tv is home to millions of internet communities, gamers, role-players, and athletes alike. With the emerging interest in live streaming on the internet, twitch has found itself being the largest online gaming streaming platform in history. A large proponent of twitch’s success on the internet is its live chat which gives its users the ability to interact with the broadcaster(streamer) in real-time using text and customized emojis, otherwise known to the community as emotes. These custom emotes are user-generated either by Twitch, Broadcasters, or Viewers. BetterTTV and FrankerFaceZ are important third-party features that allow these community-generated emotes to be used across Twitch.

Furthermore, twitch chat and its interaction with the video characteristics of broadcasts have received no attention in live streaming literature since broadcasts can go well beyond five hours. This project aims to build upon recent work regarding emote based sentiment, and community emote-profiles by including the chat interactions from the “Twitch Clip” tool. Twitch clips are user-generated “highlights” to capture important moments of the broadcast and commonly shared on platforms like YouTube and Reddit. Recently, twitch literature has begun characterizing twitch communities using twitch chat, viewership trends, and content but no known projects have used resources that exist outside of twitch to understand how twitch communities manifest and interact with one another. Studies that exist have predominantly used most viewed broadcasters with large communities to begin understanding twitch user behavior. It’s known that the size of communities on twitch plays a large role in how users behave in the chatroom. One way we can get insight into these differences between small and large communities is by analyzing reddit posts that feature “twitch clips”. One subreddit called LivestreamFails (LSF) is a dedicated subreddit where users share livestream and streamer related content. LSF is one way smaller streamers become noticed and is a platform that can be use to compare big and small communities. 

In this analysis will investigate features related to post virality (+-500 Karma) on LSF while building an R package to navigate the Twitch API and return chat information from Twitch Clips. Understanding the power of emotes and the influence that LSF has on the twitch community would be beneficial for growing streamers, company sponsors and Twitch so that they may grow the community and build products. The results are expected to extend our understanding of twitch emotes while also qualitatively and quantitatively characterizing twitch communities to improve twitch stream recommendation systems. This analysis impacts the Twitch, Reddit and R programming communties. 


# Preface

### What is a subreddit?

A subreddit can be thought of as a 'sub-community' which discuss and share topics relevant to the 'sub's' topic, name or description. For example, the coffee subreddit would be about all things coffee! It would include discussions about a specific roasting technique, coffee bean deals, or tools used to drink coffee to name a few. The subreddit that I will be investigating in this analysis is one called Livestreamfail, also know to the community as LSF. 

**LSF Picture Here**


On LSF, you can find users discussing all things related to 'livestreaming'. The discussions can range from livestreams themselves to the streamers who do the broadcasting. 

My previous analysis of LSF indicated that the majority of topics discussed were 'Twitch Clips'. 

**Plot Here**


### What are Twitch Clips and Emotes?

#### Twitch Clips

You can compare a Twitch clip to brief highlight of your favorite T.V. show with typed comments by the audience. They are short, highlighted portions of a live-broadcast that feature comments from the live-audience. 

<iframe src="https://clips.twitch.tv/embed?clip=CarefulRoundBurritoKappa-xTLV-KaURdEm9EnR&parent=www.example.com" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>

**IMAGE HERE**

Notice how in the chat box on the right, there are users who are chatting 'live' during the broadcast. Each user is different in their names, colors and 'user badges' which can signify they level of support or their role in the community. Also, notice the lack of words used in the chat box. Most users within this community use emotes instead of words. 


#### Twitch Emotes

What separates ‘live streaming’ from traditional ‘live’ TV are the interactions between the viewers and ‘streamers’ in real-time. The viewers have the ability to chat to the ‘streamer’ using plain text and emojis.. Or emotes!
Just like emojis, emotes are used to express some sort of emotion. Generally, emotes are used to react to what is being said or shown on the stream. 
But better than emojis, emotes are custom to Twitch and it’s community.

Some emotes are the same, but not all!

**Image Here**

continue describing the emotes




### Purpose of the project




### Data Collection


#### Python initial data


#### Rchamp






