---
title: "lsf_and_chat"
author: "Michael Puerto"
date: "4/12/2021"
output: html_document
---

# Reading in libraries and data

```{r, warning=FALSE,message=FALSE,error=FALSE}
library(pacman)
pacman::p_load(tidyverse,stringi,httr,fromJSON,devtools,ggthemes, tidymodels)
library(randomForest)

lsf_and_chat =read_csv('lsf_and_chat.csv')
lsf_and_chat2=read_csv('lsf_and_chat_2.csv')


lsf_and_chat<-lsf_and_chat %>% rbind(lsf_and_chat2)


```

# Exploring data

```{r}

lsf_and_chat %>% glimpse()

```

```{r}

lsf_and_chat %>% select(`Post Score`) %>% ggplot(aes(y = `Post Score`))+ geom_histogram(bins =100)

```

# Creating new variable 

```{r}

lsf_prep_data <-lsf_and_chat %>% mutate('successful' = case_when(
  `Post Score` >= 500 ~ 'successful',
  `Post Score` < 500 ~ 'not_successful')) %>% select(-c(X1,`Created UTC`,domain,url))

```

# Splitting data

```{r}
set.seed(1235)
lsf_split <- initial_split(lsf_prep_data, strata = successful)
lsf_train <- training(lsf_split)

lsf_test <- testing(lsf_split)


```

# The recipe

```{r}

lsf_recipe <- recipe(successful ~ 
first_emote+second_emote+third_emote+fourth_emote+
              first_emote_count+second_emote_count+third_emote_count+fourth_emote_count+
              first_emote_proportion+second_emote_proportion+third_emote_proportion+fourth_emote_proportion,data = lsf_train) %>%
  step_other(first_emote, threshold = 6) %>% 
  step_other(second_emote,threshold = 6) %>% 
  step_other(third_emote,threshold = 6) %>% 
  step_other(fourth_emote,threshold = 4) %>% 
  step_dummy(all_nominal(), -all_outcomes())

lsf_prep <- prep(lsf_recipe)
lsf_juice <- juice(lsf_prep)


```


# Model Specs

```{r}

lsf_specs<-rand_forest(
  mtry = 30,
  trees = 750,
  min_n = 10)%>% set_mode('classification') %>% set_engine('ranger') %>% fit(successful~., data = lsf_juice)

# use tune() for hyperparam optimization

lsf_specs_tune<-rand_forest(
  mtry = tune(),
  trees = 750,
  min_n = tune())%>% set_mode('classification') %>% set_engine('ranger')

```

# LSF workflow

```{r}

lsf_workflow<-workflow() %>% 
  add_recipe(lsf_recipe) %>% 
  add_model(lsf_specs_tune)

```


# Train hyperparams # stopped here since missing data

## 10fold -> too little data, missing some columns per hap reduce to top 10 emotes?

```{r}
set.seed(1235)
parallel::setDefaultCluster()

lsf_folds<- vfold_cv(lsf_train)

metrics_x <- metric_set(accuracy,
                      sens,spec,roc_auc)


grid_rf <- grid_regular(
  mtry(range = c(15,20)),
  min_n(range =c(10,20)),
  levels = 5
)

tune_lsf<-tune_grid(
  lsf_workflow,
  resamples = lsf_folds,
  grid = grid_rf,
  metrics = metrics_x)


```


```{r}

lsf_test_2 <- lsf_prep %>% bake(lsf_test)


lsf_specs %>% predict(lsf_test_2) %>% bind_cols(lsf_test_2) %>% metrics(truth = successful, estimate=.pred_class)

```


```{r}

tune_lsf %>%
  collect_metrics() %>%
  filter(.metric == "roc_auc") %>%
  mutate(min_n = factor(min_n)) %>%
  ggplot(aes(mtry, mean, color = min_n)) +
  geom_line(alpha = 0.5, size = 1.5) +
  geom_point() +
  labs(y = "AUC")

```


```{r}
best_auc <- select_best(tune_lsf,'roc_auc')

final_model <- finalize_model(
  lsf_specs_tune,
  best_auc)
library(vip)
final_model %>% 
  set_engine("ranger", importance = "permutation") %>%
  fit(successful ~ .,
    data = juice(lsf_prep)) %>%
  vip(geom = "point")

```

```{r}

final_workflow<- workflow() %>% 
  add_recipe(lsf_recipe) %>% 
  add_model(final_model)

final <- final_workflow %>% 
  last_fit(lsf_split)

final %>% 
  collect_metrics()


```
```{r}
tune_lsf %>% collect_metrics() %>% filter(mtry==15,min_n==10)




```


